services:
  # A Docker web service
  - type: web
    name: "CamKow Analytics Dashboard"
    runtime: docker
    repo: https://github.com/willkrakow/fathom-analytics
    branch: master
    envVars:
      - key: FATHOM_GZIP
        value: true
      - key: FATHOM_DEBUG
        value: false
      - key: FATHOM_DATABASE_DRIVER
        value: postgres
      - key: FATHOM_DATABASE_NAME
        fromDatabase:
          name: "CamKow Analytics"
          property: database
      - key: FATHOM_DATABASE_USER
        fromDatabase:
          name: "CamKow Analytics"
          property: user
      - key: FATHOM_DATABASE_PASSWORD
        fromDatabase:
          name: "CamKow Analytics"
          property: password
      - key: FATHOM_DATABASE_HOST
        fromDatabase:
          name: "CamKow Analytics"
          property: host
      - key: FATHOM_SECRET
        sync: false
  - type: web
    name: talebygale-data
    runtime: image
    image:
      url: docker.io/nocodb/nocodb:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: "TaleByGale"
          property: connectionString
      - key: PORT
        value: 8080
  - type: web
    name: talebygale-sync
    runtime: node
    repo: https://github.com/willkrakow/talebygale-sync
    buildCommand: "npm install"
    startCommand: "tsx src/index.ts"
    envVars:
      - key: NODE_VERSION
        value: 18.12.1
      - fromGroup: stripe-api
      - fromGroup: ghost-api
      - fromGroup: nocodb-api

  # A Python cron job that runs every hour
  - type: cron
    name: talebygale-cron
    runtime: node
    schedule: "0 */8 * * *"
    buildCommand: "npm install" # ensure it's a string
    startCommand: tsx src/index.ts
    repo: https://github.com/willkrakow/talebygale-cron
    envVars:
      - key: LAURA_PHONE_NUMBER
        value: +19199239882
      - key: MY_PHONE_NUMBER
        value: +19199239882
      - key: NODE_VERSION
        value: 18.12.1
      - fromGroup: ghost-api
      - fromGroup: twilio-api

databases:
  - name: CamKow Analytics
    databaseName: atbg_analytics
    user: laura
  - name: TaleByGale
    databaseName: tale_by_gale
    user: laura

envVarGroups:
  - name: ghost-api
    envVars:
      - key: GHOST_API_KEY
        sync: false
      - key: GHOST_API_URL
        value: https://atalebygale.ghost.io
      - key: GHOST_CONTENT_API_KEY
        sync: false
  - name: stripe-api
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY__TEST
        sync: false
      - key: STRIPE_WEBHOOK_SECRET__TEST
        sync: false
  - name: nocodb-api
    envVars:
      - key: NOCODB_API_KEY
        sync: false
      - key: NOCODB_API_URL
        value: https://data.talebygale.com
      - key: NOCO_ORG
        value: TaleByGale
      - key: NOCO_PROJECT
        value: p_7blljqhz7g4srs
  - name: twilio-api
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
